### PR TITLE
feat: Add RON currency

### PR DESCRIPTION
**Pull request by antiquitte**
Signed-off-by: CatalinBoiangiu catalin.boiangiu@lansoft.ro

Adds RON currency.

### CODE REVIEW

**Comment by mikemurray** [comment]
@CatalinBoiangiu Could you update your commit message to `feat: Add RON currency`. We use semantic release and auto deploy on merge to `npm` and need the prefix `feat: ` to do that.

(Also pushing again should make the build run again and hopefully pass)

**Comment by antiquitte** [comment]
Should be all good now.

**Review by mikemurray — APPROVED** [review]
👍 LGTM. 

Ran the test locally and they all pass. Not sure why the build is failing on CI.

**Pull request merged**
