### PR TITLE
[WIP] Add offset support for `arrayJoinPlusRemainingQuery`

### LINKED ISSUE #6514: `arrayJoinPlusRemainingQuery` doesn't consider `offset` parameter for pagination.
[arrayJoinPlusRemainingQuery.js#L238](https://github.com/reactioncommerce/api-utils/blob/trunk/lib/arrayJoinPlusRemainingQuery.js#L238) doesn't support offset parameter in cursor. 
Its used at following places:
1. [catalogItemsAggregate](https://github.com//reactioncommerce/reaction/blob/0f9fef20fb50087b51fb74c23e8608f4e7a246ac/src/core-services/catalog/queries/catalogItemsAggregate.js#L38)
2. [productsByTagId#L22](https://github.com//reactioncommerce/reaction/blob/bffb304f2ec3a64a77f13b2942aad40ceab492f1/src/core-services/tags/queries/productsByTagId.js#L22)

We need to consider the `offset` parameter and skip the `nodeItems` accordingly.

### PR DESCRIPTION
**Pull request by trojanh**
resolves: https://github.com/reactioncommerce/reaction/issues/6514

Currently `arrayJoinPlusRemainingQuery` does not consider `offset` in `connectionArgs`.

- [ ]  Write test case for existing `arrayJoinPlusRemainingQuery` file

- [ ]  Fix `arrayJoinPlusRemainingQuery` to consider `offset` and update the test to reflect the same.

### CODE REVIEW

**Comment by trojanh** [comment]
@aldeed could you help me with this test, how do you think should I mock the `joinCollection.find` calls accurately?

**Comment by aldeed** [comment]
@trojanh I'll need to look at this after I wrap up some 3.0 work. I think to properly test this we will want to use a mock or real MongoDB instance rather than mock the collection calls, but I need to figure out what our approach will be for that.

**Comment by trojanh** [comment]
awesome @aldeed , this is very important as we don't have many test cases to cover such scenarios in the API.

**Comment by Akarshit** [comment]
Closing because of age.

**Pull request closed without merging**
