### PR TITLE
(fix) remove deprecated export style

### LINKED ISSUE #83: Deprecation warnings in Node 16
When using Node 16 using this plugin gives you this warning for every plugin that uses it:
```
[DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module 
```

### PR DESCRIPTION
**Pull request by brent-hoover**
Resolves: https://github.com/reactioncommerce/api-utils/issues/83

### CODE REVIEW

**Comment by zenweasel** [comment]
As usual, build is broken and the output to see why it's broken, is also broken

**Comment by Akarshit** [comment]
@zenweasel Not sure what was the issue, when I ran this again it worked.
Also can you please format the commit message like: "fix: remove deprecated export style"

**Comment by brent-hoover** [comment]
@Akarshit We may need to revert this as I am running into issues with this in some cases. Unclear why

**Comment by brent-hoover** [comment]
Getting this error all of a sudden: 
```
 Directory import <path>is not supported resolving ES modules imported from <path>/authorization/schemas/index.js
 ```

**Comment by Akarshit** [comment]
@zenweasel Lol, do you want me to revert this or are you creating a PR for this?

**Comment by brent-hoover** [comment]
I have already deleted my repo so you'll need to revert it. Apologies

**Comment by Akarshit** [comment]
No worries, I will get this reverted. Thanks for the report :)

**Pull request merged**
