### PR TITLE
Add Mongolian

### PR DESCRIPTION
**Pull request by endigo**
FIX: Use the correct name of the capital of Mongolia.
Add MNT
Add Mongolian to LanguageOptions

### CODE REVIEW

**Comment by endigo** [comment]
cc @aldeed @kieckhafer

**Review by aldeed — CHANGES_REQUESTED** [review]
@endigo You'll need to remove all the trailing commas you added. Reaction style guide does not allow them. For some reason CI is not running that check on this repo, which we'll have to fix. But in the meantime just run `npm run lint` locally and verify you get no errors.

Otherwise this should be okay to merge.

**Comment by endigo** [comment]
@aldeed please review it again.

**Review by aldeed — APPROVED** [review]

**Pull request merged**
