### PR TITLE
Fix `totalCount` on `getPaginatedResponseFromAggregate`

### LINKED ISSUE #80: `totalCount` always equals `1` when using `getPaginatedResponseFromAggregate`
I've recently noticed that, no matter what pipeline you pass it, `getPaginatedResponseFromAggregate` seems to always return `totalCount: 1`.

The issue is that the `$addFields` stage that we're currently using doesn't seem to work anymore for calculating the number of objects returned.

### PR DESCRIPTION
**Pull request by loan-laux**
Fixes #80

This PR implements `totalCount` in a way that actually works with all aggregates.

Unfortunately, the `.count()` cursor method (which we use to get the `totalCount` on normal, non-aggregate queries) is not available on aggregates. This is why we've had to resort to using `$addFields` with a `$sum` operator in the past to get the total number of objects returned by a given aggregate.

This doesn't seem to work anymore, as `getPaginatedResponseFromAggregate` always seems to return `totalCount: 1`.

My new implementation seems to be the only reliable way to count the total number of returned objects with an aggregate. I've detailed it with comments directly in the code, but I'll give a breakdown here as well:

## Stage 1: `$group` into a single array

We group all of the objects returned by the pipeline at this point into a single array, in a single object. This allows us to add a `totalCount` field that is the `$sum` of that array, giving us the total number of objects.

## Stage 2: `$unwind` to get back our individual objects

Stage 1 leaves us with a single object and all of our results in a single array. We obviously want individual objects, so we use `$unwind` on that array.

## Stage 3: `$set` our `totalCount` field inside the unwinded object

At the end of Stage 2, we have our `totalCount` field, but it's outside of our object. Because we're going to `$replaceRoot` with that object in the next stage, we want to move out `totalCount` field into this object so we don't lose it.

## Stage 4: `$replaceRoot` to get a clean, non-nested result

We use `$replaceRoot` to have a result that only returns the objects that the pipeline would have otherwise returned, with the only difference that all objects now have a `totalCount` field with the total count of returned objects.

If this pipeline for `totalCount` isn't clear with my comments, I would recommend checking it out stage by stage with MongoDB Compass. Things will make more sense by being able to see what happens at every stage.

### CODE REVIEW

**Comment by Akarshit** [comment]
@loan-laux Looks neat! Do you think we can include a test case for this? I am sure someone is going to break this someday...

**Comment by loan-laux** [comment]
@Akarshit There's an update to the original test case for `totalCount` as part of this PR. Is that okay or did you have something else in mind?

**Comment by Akarshit** [comment]
Yeah, I missed it somehow.

**Pull request merged**
